apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-timeline-settings
spec:
  forms:
    - group: base
      label: 基本设置
      formSchema:
        - $el: a
          attrs:
            href: "https://www.lik.cc/docs/halo-plugins"
            class: "py-4 block"
            target: "_blank"
            style:
              color: "#1890ff"
              fontSize: "0.875em"
              display: "flex"
              align-items: "center"
          children:
            - $el: span
              children: "查看 足迹 帮助文档"
            - $el: img
              attrs:
                src: "/plugins/footprint/assets/static/img/link.svg"
                width: "14px"
                height: "14px"
                style:
                  margin-left: "4px"
        - $el: a
          attrs:
            href: "https://www.lik.cc/archives/microimmersion"
            class: "py-4 block"
            target: "_blank"
            style:
              color: "#1890ff"
              fontSize: "0.875em"
              display: "flex"
              align-items: "center"
          children:
            - $el: span
              children: "推荐halo主题"
            - $el: img
              attrs:
                src: "/plugins/footprint/assets/static/img/link.svg"
                width: "14px"
                height: "14px"
                style:
                  margin-left: "4px"
        - $el: span
          children: "加入交流群"
        - $el: img
          attrs:
            src: "https://www.lik.cc/upload/iShot_2025-03-03_16.03.00.png"
            width: "100px"
            height: "120px"
            style:
              margin-left: "80px"
        - $formkit: text
          label: 页面标题
          name: title
          validation: required
          value: '我的足迹'
          help: "这里是你的网址标题"
        - $formkit: text
          label: 左下角标题
          name: logoName
          validation: required
          value: '足迹'
          help: "这里是左下角的标题"
        - $formkit: text
          label: 足迹描述
          name: describe
          validation: required
          value: '每一处足迹都充满了故事，那是对人生的思考和无限的风光。'
          help: "这里是左下角的描述"
        - $formkit: text
          label: hsl颜色值
          name: hsla
          validation: required
          value: '109,68%,60%'
          help: "全局配色 HSL格式：322,68%,60% (色相去掉deg,数值之间不要有空格)"
        - $formkit: text
          label: 高德JsKey
          name: gaoDeKey
          validation: required
          help: https://console.amap.com/dev/key/app 前往获取 主要用于创建地图
        - $formkit: text
          label: 高德WebKey
          name: gaoDeWebKey
          validation: required
          help: https://console.amap.com/dev/key/app 前往获取 用户自动获取经纬度
        - $formkit: select
          name: mapStyle
          label: 地图样式
          sortable: true
          clearable: true
          searchable: true
          placeholder: 请选择你的主题
          options:
            - label: 标准
              value: amap://styles/normal
            - label: 幻影黑
              value: amap://styles/dark
            - label: 月光银
              value: amap://styles/light
            - label: 远山黛
              value: amap://styles/whitesmoke
            - label: 草色青
              value: amap://styles/fresh
            - label: 雅士灰
              value: amap://styles/grey
            - label: 涂鸦
              value: amap://styles/graffiti
            - label: 马卡龙
              value: amap://styles/macaron
            - label: 靛青蓝
              value: amap://styles/blue
            - label: 极夜蓝
              value: amap://styles/darkblue
            - label: 酱籽
              value: amap://styles/wine

    - group: advanced
      label: 高级设置
      formSchema:
        - $formkit: list
          name: footprintTypes
          label: 足迹类型
          addLabel: 添加类型
          min: 1
          value: ["旅游", "美食", "购物", "住宿", "交通", "其他"]
          help: "自定义足迹类型"
          itemType: string
          children:
            - $formkit: text
              index: "$index"
              validation: required
