apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-timeline-settings
spec:
  forms:
    - group: base
      label: 基本设置
      formSchema:
        - $el: a
          attrs:
            href: "https://www.lik.cc/docs/halo-plugins"
            class: "py-4 block"
            target: "_blank"
            style:
              color: "#1890ff"
              fontSize: "0.875em"
              display: "flex"
              align-items: "center"
          children:
            - $el: span
              children: "查看 时间轴 帮助文档"
            - $el: img
              attrs:
                src: "/plugins/timeline/assets/static/img/link.svg"
                width: "14px"
                height: "14px"
                style:
                  margin-left: "4px"
        - $el: span
          children: "加入交流群"
        - $el: img
          attrs:
            src: "https://www.lik.cc/upload/iShot_2025-03-03_16.03.00.png"
            width: "100px"
            height: "120px"
            style:
              margin-left: "80px"
        - $formkit: text
          label: 时间轴
          name: title
          validation: required
          value: '时间轴'
          help: "这里是你的网址标题"
        - $formkit: range
          label: '背景透明度(0为完全透明, 1为不透明)'
          id: opacity_val
          name: opacity_val
          value: '0.5'
          min: 0
          step: 0.05
          max: 1
          help: $get(opacity_val).value
        - $formkit: attachment
          label: 背景图片
          name: bgImages
          id: bgImages
          key: bgImages
          value: "https://assets.codepen.io/3364143/7btrrd.mp4"
          help: 支持视频背景和图片

    - group: advanced
      label: 高级设置
      formSchema:
        - $formkit: list
          name: timelineTypes
          label: 时间轴类型
          addLabel: 添加类型
          min: 1
          value: ["建站历程", "普通时间", "学习历程"]
          help: "自定义时间轴类型"
          itemType: string
          children:
            - $formkit: text
              index: "$index"
              validation: required
